### ISSUE TITLE
[Suggestion] Enable/Disable Ore/block generation

### ISSUE THREAD

**Issue by logicsequence** [Povstalec/StargateJourney#14]
Just got a chance to check out the mod, i'm loving the work so far!  I was wondering though, i could see a situation where i might want to use this mod on my sever in an alternative way.  We have many areas separated by 10,000s of blocks, which we currently use waystones to go between.  I'd love to use stargates, which is possible with this mod and 9-symbol addresses.  But my concern is block generation.  I'd rather setup the stargate "network" myself than leave it to the players.  It would be great if there was an option to enable/disable the generation of blocks like ores.  That way, if one wanted, they could create a stargate network that generated naturally, and/or was built by the admins, without involving other players or dealing with ore issues in previously generated chunks, etc.

**Comment by Povstalec** [comment]
All of the generation in the mod is fully Datapack compatible, so if you want to disable ore generation on Abydos for example, all that's needed is to remove the "sgjourney:ore_naquadah" from features in Abydos Biomes, for example the [Abydos Desert Biome](https://github.com/Povstalec/StargateJourney/blob/main/src/main/resources/data/sgjourney/worldgen/biome/abydos_desert.json#L70).
For structure generation, all that's required is changing a [tag](https://github.com/Povstalec/StargateJourney/blob/main/src/main/resources/data/sgjourney/tags/worldgen/biome/has_structure/goauld_temple/desert_pyramid_biomes.json#L6) by removing the biomes a structure can generate in.

Though I'm not sure what exactly the concern with ores generation is, since sgjourney doesn't change Vanilla oregen and (outside of structures) I try to leave the Overworld intact.

**Comment by logicsequence** [comment]
Well it's more about not spawning ores that won't be used, since i would be planning to manage the stargate network myself, and not have it be something players build, etc.  In fact i would probably disable spawning of gates in the overworld entirely, and place them myself manually.  Just a preference of how to do it on my specific server, obviously the way you have it set up is probably what most people would want, but i thought there might be a few who would want some more admin manageability or role-play aspect to it. 

P.S.
Would be cool for admins to be able to manually edit a gate's address too, perhaps like creative only admin tool, click on a gate, edit it's attributes, etc...  Just a thought.

**Comment by Povstalec** [comment]
Sorry, but I still don't quite understand what exactly you want. Datapacks are the best way to adjust how the game works, since they allow you to specify, change and add everything in much greater detail than config options could ever allow. 

I've made a Datapack for [Disabling Naquadah Generation](https://github.com/Povstalec/StargateJourney-Datapacks/tree/main/Disabled%20Naquadah%20Generation) and  [Stargate generation](https://github.com/Povstalec/StargateJourney-Datapacks/tree/main/Disabled%20Stargate%20Generation) altogether. I assume that's what you're looking for. Effectively all that's needed is to put them in the world's datapack folder and have them enabled.

I like the idea, so I will probably add some way to do manually edit a gate's address, but it's gonna be a while until I roll out the update, so in the meanwhile, you can use this command to get a gate address of your liking
**/give @p sgjourney:milky_way_stargate{BlockEntityTag:{ID:"-1-2-3-4-5-6-7-8-"}}**
(Note that the dashes are an important part of the address and must all be present, otherwise the address may not work or will generate automatically)

And yes, Naquadah does not generate in the Overworld naturally, it currently only generated on Abydos
