### ISSUE TITLE
If a Stargate is placed by command it will nio added to to BlockEntityList

### ISSUE THREAD

**Issue by darthzapp** [Povstalec/StargateJourney#144]
**Describe the bug**

To start at the beginning... I want to use stargates in my modpack because they are the only way to travel between dimensions, so I need a functional stargate in some dimensions like the nether or the Twilight Forest and some ad astra planets and datapack dimensions, etc. So I created a structure that will be placed via Kubejs in these dimensions... But the Stargates won't work.

It's like the title says if a stargate is placed by command, it will not be added to the BlockEntityList.
I placed a command_block in a structure because the structure keeps the nbt data of the Stargate, so I tried it with a commandblock, so an unknown error occurred if you used the PDA and the console said nothing and sent an error by breaking the Stargate.

                21:30:41.126 net.povstalec.sgjourney.StargateJourney Server thread Couldn't find Stargate
                21:30:41.127 net.povstalec.sgjourney.StargateJourney Server thread - not found in BlockEntityList
                21:30:41.127 net.povstalec.sgjourney.StargateJourney Server thread Removed - from Stargate Network

**Ideas to fix**
a check for every block it's a stargate at being placed?? 
or a block for structures that one creates stargates

Okay, I was a bit fast because I noticed you use the pedastals to spawn stargates.

**Comment by Povstalec** [comment]
This is not a bug, it's a completely intentional workaround to make Stargates work properly, even when Minecraft would not normally allow it.

When you're making your Structure, you need to use the Stargate that you can find in the Operator Items Creative Tab (If you don't know where it is, here is a [video that shows how to enable it](https://youtu.be/C2cP9-BM2bg?t=92)).

When you place a regular Stargate, it generates ALL of its info, that means the Address, Point of Origin, Symbols and so on. There exists no way to make sure this info can change when the Stargate is then randomly generated inside a Structure during gameplay, as the info would still be a copy of the info in the Stargate you placed, meaning it would be IMPOSSIBLE to have it generate Symbols and Point of Origin based on the dimension it generated in.

So as you can see, such a Stargate is NOT what you want to be copying into Structures.

Instead, use the Operator Stargate. The Operator Stargate is completely clean - it has no info other than what is absolutely necessary, and it is programmed to generate its info the NEXT TIME it loads, meaning if you place it inside your custom Structure and save it, this clean Stargate will then be used during generation and you are guaranteed to get a new unique Stargate each time your Structure generates during gameplay.

**Comment by darthzapp** [comment]
Thank you a lot. That explains why the pedestals won't be added to the network if they're getting placed via command.
