### ISSUE TITLE
No cartouche

### ISSUE THREAD

**Issue by Yukkun** [Povstalec/StargateJourney#34]
I found my first stargate, but there is no cartouche for the Abydos address anywhere. I had to use console commands to find out the address.
Not sure if it didn't spawn because some Biomes O'Plenty tree decided to also spawn right on top of the stargate. Just think it would probably better to hide the cartouche somewhere better, or make Abydos cartouche something the villager sells too with the map.

**Comment by Povstalec** [comment]
> I found my first stargate, but there is no cartouche for the Abydos address anywhere.

Are you playing All The Mods 9? If that's the case then [regular Stargate Pedestals and Cartouches generate separately](https://github.com/Povstalec/StargateJourney/wiki/Frequently-Asked-Questions-(FAQ)#im-playing-with-all-the-mods-9-and-ive-found-the-stargate-but-there-is-no-cartouche-nearby)

**Comment by Povstalec** [comment]
> No, custom modpack. Forgot that mention that. Oh and using latest version of the mod. 0.6.8 I think it was

In that case you've found the regular Stargate Pedestal with Beta gate.

Yeah, it's kind of a bug that the map can lead to the Beta gate, since it should ideally only lead to the buried Alpha gate. 

The buried gate is still around somewhere around your world, but since you've already solved the lack of address, unless you specifically want the Stargate with the pyramid symbol, there's no need to make wild attempts at getting around the issue.

While I have no way to change it on currently existing worlds, I have already started making changes that should hopefully prevent it from happening in newly generated worlds.
