### ISSUE TITLE
basic_interface + stargate consumes to much power at standby

### ISSUE THREAD

**Issue by Pyrenos** [Povstalec/StargateJourney#43]
I have a problem with the basic_interface, which directs large amounts of energy into standby mode for the Stargate. I'm playing with the Mekanism mod, and the energy consumption is just abnormally high. It should only consume energy when active, not in standby mode. It would also be helpful if the basic_interface could be placed under the Stargate. If you place the power cable on the 'bottom' side of the basic_interface, only sides in the immediate visible area remain for placing the network cable from CC, which hardly looks nice. Furthermore, I have looked at the API for dialing and, unfortunately, can only give negative feedback. Hardly anyone plays CC, so all operations on CC should be as simple as possible. It's not beneficial if a beginner is deterred by this unnecessarily complicated rotation of an address. It should be uniform and simple.

Please revise your documentation to make it understandable how it works. This lackluster documentation just doesn't match the outstanding quality of the mod.

**Comment by Pyrenos** [comment]
Pictures to examples of possible setups as well as CC code would also be very helpful.

**Comment by Povstalec** [comment]
Alright, so first things first, Stargate doesn't consume the power, it just stores it and consumes it later when it's connected. It can hold like 500 000 000 000 000 FE or so, so to the outside world it may look like the energy is just endlessly going nowhere. Yes, the Basic Interface would benefit from a check that by default stops feeding the gate power after a certain amount and can be disabled if you want to feed the gate more power, that is one of the things that should be added in 0.6.9.

> It would also be helpful if the basic_interface could be placed under the Stargate
I'm not sure what you mean by this. You can place the interface literally anywhere as long as the front is directly facing the gate, even above or below the gate.

> all operations on CC should be as simple as possible

I kinda agree and kinda disagree. I do very much agree that there should be a simple way to automatize manual dialing, that's why I want to make a custom dialing computer that will be able to dial the gate without needing to be programmed.  

But I disagree that it should be as simple as possible. 

The reasoning mostly comes from lore: Basic Interface is too "primitive" to interface with the Milky Way Stargate directly. It can't just tell the gate to "dial this address" because the gate wouldn't understand anything. But the gate does understand basic redstone signals and that's essentially what the Basic Interface is using to communicate. So just like in the series, where they were basically moving the ring with a motor and sending electric signals to lock chevron, this way of operating the Stargate is also supposed to feel very basic, but have lots of room for adjusting it.

It already is very simple to use from a programming point of view. You have the most basic pieces of code: "rotate this way" "stop" "lock" and all you need is to put them together in a way you like.In its simplest form, the program is just a loop that activates functions in a specific order until all chevrons are locked.

Something like adding a function that automatically does all the dialing for you (which I do have planned for the Classic Stargate, because it's based on the old SG-Craft Stargate which basically did exactly that) would just remove everything that's interesting and challenging about creating your own dialing program.

So all in all, yes, I do recognize it was a very bad design decision on my end to rely on CC: Tweaked as a main method of manual dialing without providing a simpler alternative, since spinning is what most people remember when they think of a Stargate. For all intents and purposes, I do still intend to keep the Basic Interface functionality as it is now, but I will add an alternative to it for anyone who doesn't want to get a headache trying to get a dialing program to work.

I don't have pictures, but there is a video covering hopefully most of the important stuff: https://www.youtube.com/watch?v=qNi9NUAmOJM
and there is also an example program that can be found in FAQ: https://github.com/Povstalec/StargateJourney/wiki/Frequently-Asked-Questions-%28FAQ%29#is-there-an-example-of-a-computercraft-dialing-program

**Comment by Povstalec** [comment]
But yes, I am well aware of the terrible documentation I make. Since I keep on changing stuff all the time, about 50% of the stuff on the wiki is outdated within a month because I forget to write the changes down. Other times I don't write a page at all since the object in question is very work in progress, so it would be outdated within a day or two.

So, if you could list me specific missing info you were looking for, I can go and fill it in for some time at least until it's outdated again.

**Comment by Pyrenos** [comment]
Okay, thank you very much for the feedback and the help. I will test this out. The video is very good; you should include it in the documentation. I will now diligently test. Thanks again.
