### ISSUE TITLE
Stargate spawning at the bottom of deep oceans, and a couple other remarks.

### ISSUE THREAD

**Issue by DexLuther** [Povstalec/StargateJourney#46]
As the title says. It was my first try of of this mod, I like it so far. Is this mod based on, a rewrite of previous Statgate mods that have not updated past 1.12, or completely original?

Anyways, as I said, it was my first outing with this mod and I decided to add it to the Direwolf 1.20.1 FTB pack. 

I used the datapack to make stargates more common, but flying around in creative mode I was not able to spot a single one. One thing to note is that when activating the datapack, it said that it was incompatible with the current version, and didn't seem to function. I used the command to give the addresses of the overworld gates and it only listed one. I was unable to find any information on where to put the datapack, so I assumed it went into Resouse packs like everything else does (I assume this is wrong).

Next, I progressed in survival mode. Eventually got the map to the Ring of the Gods. It wasn't too far, but out in the middle of nowhere in the ocean.

Tried to get down there, but would require a lot of equipment I didn't have yet. I decided to turn creative on again and dig down where the X was and found nothing. I eventually started using an Iron Hammer to excavate larger portions of the area getting all the way down to bedrock. Found nothing and accidentally broke the bedrock and fell out of the world. 

I ended up having to revert to a backup and redo the map-getting portion and get to the spot. I eventually found it. Seemed to be some kind of half-buried temple. There was also a weird island with trees underwater. I'm guessing the gate island/temple thing generated too early and then got partially overwritten (seems to happen a lot with vanilla villages).

Ended up having to block off a portion and then use a creative sponge to get rid of the water.

It's cool that the gate is buried, but it probably shouldn't be underwater. At least not that deep. A few blocks worth of flooding is probably ok.

I also don't know if I didn't install the common gates datapack correctly or it just doesn't work on 1.20.1

**Comment by Povstalec** [comment]
The mod is original, although there are aspects (like the Classic Stargate), which are inspired by older Stargate mods.

Yeah, you put the datapack in the incorrect place, that's why it said it was incompatible. If you navigate to your **saves** folder, inside each world folder there is a **datapacks** folder and that's where the datapacks go. The Minecraft wiki explains it in further detail: https://minecraft.wiki/w/Tutorials/Installing_a_data_pack

Not sure what happened with the trees underwater, probably some kind of weird quirk of Minecraft worldgen I have no control over.

Unfortunately, there is no way for me to make sure the gate doesn't generate underwater . The problem lies in the fact that default Minecraft Structure generation is not adjusted to generating only one Structure per dimension. What the mod does is it generates random coordinates for the Stargate and then only allows generating that Structure in those specific coordinates. There are things I'm trying in 0.6.9 to at least make sure it doesn't happen often, like locating nearest ideal biome and moving the generation coordinates there, but since it's not guaranteed those biomes will be within location distance, there is no way to truly get rid of the problem without risking the gate won't generate at all.

**Comment by Povstalec** [comment]
I'm actually quite against using config over Datapacks in this case. Yes, it is a trade-off for convenience and using Datapacks is a more complicated than going into the config and changing a few values, but in return Datapacks offer 10 000 000 000 times more customizability than what config could ever provide.

Stargates generating in Villages, changing the probability of a Structure generating, changing where the Structure generates... all of that can be fairly quickly done in a Datapack, not to mention being able to add new stuff like new Dimensions, Biomes or Structures. Or if we take stuff you can add specifically to sgjourney, you can add Galaxies, Solar Systems, Symbols, Points of Origin and even Stargate Variants (coming in v0.6.9).

While I generally prefer to make most individual gameplay mechanics customizable through Config, I think something more complex, like Structure generation for example, should be controlled with Datapacks, because as long as one takes the time to understand how to use them, they become an incerdibly powerful tool.

> It's weird Villages and some other structures tend to get decimated by World Gen, but Illager Towers seem to always make it through more or less perfectly.

> The Goa'uld temples also seem to make it through perfectly. I haven't found a single one underwater or destroyed in any way.

The reason Goa'uld Temples generate fine is simple: There isn't just one. That's it. If a Goa'uld Temple attempts to generate at a location that isn't suitable (underwater, for example), it just doesn't get generated at all. There are many Goa'uld Temples in the world, so you can afford to not generate a few from time to time, because nobody will notice anyway. That's how Vanilla Minecraft Structure generation works too.

The only problem for Vanilla are Villages, which don't generate in one piece, but in multiple pieces which copy terrain and start generating from some central piece. There is a check whether or not the place is suitable for the central piece to generate, but any other pieces just don't really care and generate however RNG tells them to.
