### ISSUE TITLE
Gate not closing

### ISSUE THREAD

**Issue by AlmightyAnubis** [Povstalec/StargateJourney#70]
Currently playing ATM9. After my last trip to abydos, the gate didn't close it seems. I don't really know what to do, since I guess the chunk needs to be loaded, so it can close, but I cant load the chunk since I cant get there...

Would it be possible, to automaticly close a gate when it gets a connection request from the gate it thinks it is connected to. That would not be perfect, but a quick solution. The other option would be to forceload the chunk of the gate until it has closed.

I really love the mod. Even wrote my own Computer craft program to use a screen for dialing. But without abydos you can't naquadah for all the tec. Maybe a naquadah bee would be nice, but this might be on the side of the productiv bees mod

**Comment by AlmightyAnubis** [comment]
v 0.6.17 Hotfix

**Comment by Povstalec** [comment]
It does not need the chunk to be loaded by any players, because that's something handled by the Stargate Network. The gate already has an autoclose feature for when a Large Control Crystal is placed inside a DHD, but with the default config (which ATM9 should be using I think), you should be able to force-close it by pressing the big red button on the DHD on either side of the connection.

If none of that works, then the problem runs much deeper and you can fix it by following this: https://github.com/Povstalec/StargateJourney/wiki/Troubleshooting#stargate-is-not-dialingnot-disconnectingcausing-any-kind-of-trouble

**Comment by AlmightyAnubis** [comment]
Does the auto close also apply to closing the gate with computer craft?

**Comment by WinMister332** [comment]
You're forgetting something, a black hole. That'll keep the gate open indefinitely. That or the power of 10 ZPM's.

**Comment by Povstalec** [comment]
First part isn't in the mod, second part is. But it's locked behind a config.

**Comment by AlmightyAnubis** [comment]
Would it be possible to close the gate or reconnect it, if the gate that is should be connected to dials it? So if abydos thinks, earth is connected and earth dials in, the gate connects

**Comment by WinMister332** [comment]
> First part isn't in the mod, second part is. But it's locked behind a config.

I was making a joke.

**Comment by WinMister332** [comment]
> > Would it be possible to close the gate or reconnect it, if the gate that is should be connected to dials it? So if abydos thinks, earth is connected and earth dials in, the gate connects
> 
> Can you explain it in more depth please? I'm not sure I understand what you mean

I could be wrong, but I think they mean dialing into a gate from the very gate the other gate is already connected to. Like trying to establish a connection with the Abydos gate from the earth-gate eventhough the Earth gate is already connected to abydos. (Or at least make the gate think it's been redirected)

But can't you just press the button on the DHD to close the gate?

**Comment by Povstalec** [comment]
> > > Would it be possible to close the gate or reconnect it, if the gate that is should be connected to dials it? So if abydos thinks, earth is connected and earth dials in, the gate connects
> > 
> > 
> > Can you explain it in more depth please? I'm not sure I understand what you mean
> 
> I could be wrong, but I think they mean dialing into a gate from the very gate the other gate is already connected to. Like trying to establish a connection with the Abydos gate from the earth-gate eventhough the Earth gate is already connected to abydos. (Or at least make the gate think it's been redirected)

So like... essentially switch the direction of the wormhole? Because I don't see any use for it other than that.

> But can't you just press the button on the DHD to close the gate?

That's exactly what you can do. And for those who don't like having to dial back, there's the config option to make wormholes work in both directions.

**Comment by AlmightyAnubis** [comment]
The issue was, that the earth gate was closed, but the abydos gate still though it was connect, not allowing a new connection. Not allowing a connection while connected is logical. But when the connection comes from the gate it thinks it is connected to is should go through

**Comment by Povstalec** [comment]
Ahh, I see. Well, what you've suggested would not be a great solution,considering the fact it only covers the cases of trying to connect the same gate, while ignoring all other problems like not allowing other gates to connect, because at that point, the problematic gate in question SHOULD NOT be connected, even though it is.

But don't worry, I've got a better solution already implemented in the newest development version.
