### ISSUE TITLE
Some strange message at the start of the game

### ISSUE THREAD

**Issue by Krimatoria** [Povstalec/StargateJourney#82]
Stargate Journey-1.19.2-0.6.20.jar
What does this mean? Stargate does not have enough space 
![2024-02-23_03 48 19](https://github.com/Povstalec/StargateJourney/assets/106809386/de774237-8b2e-470c-ac40-77d9a8eac81b)
![2024-02-23_03 48 13](https://github.com/Povstalec/StargateJourney/assets/106809386/e70e8dc7-2adf-47e6-bc86-1e7e8ad9d49f)

**Comment by Povstalec** [comment]
[Related to this](https://github.com/Povstalec/StargateJourney/issues/68)

I have little to no idea why it's happening because the message should only ever be physically shown when you're trying to place a Stargate, so I have no clue how any other mod could possibly be accessing that code and running it somehow.
