### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Vadewolf** [Povstalec/StargateJourney#83]
is it possible by default to find every dimension cartouche from this mod? jw cause ive not found any for chulak or lantea or tenebrae

**Comment by Povstalec** [comment]
It is (except for Lantea). If you haven't found any addresses to the other Dimensions while walking around Abydos, you probably just got really unlucky.

**Comment by Povstalec** [comment]
I want to add a separate structure that will hold addresses for modded dimensions + Nether and End and leave only sgjourney dimensions in the current structure, which should hopefully make finding addresses for sgjourney dimensions easier.

**Comment by Vadewolf** [comment]
if ure making cartouche changes can u make them a bit easier to find on abydos by chance? cause rn having to go like thousands of blocks to find one cartouche and it be a duplicate of the one ive found already is really annoying and impossible to see when using sandstone on sand

**Comment by Povstalec** [comment]
maybe

**Comment by Vadewolf** [comment]
just a suggestion but cartouche wise it would help trmendously if there wernt cartouches for mods that arent in a pack

**Comment by tehgreatdoge** [comment]
> just a suggestion but cartouche wise it would help trmendously if there wernt cartouches for mods that arent in a pack

Wdym? The cartouches only give addresses to dimensions that are in your pack, and like wold said, he is going to make there be separate cartouches for the sgjourney, overworld, and generated addresses.

**Comment by Vadewolf** [comment]
> > just a suggestion but cartouche wise it would help trmendously if there wernt cartouches for mods that arent in a pack
> 
> Wdym? The cartouches only give addresses to dimensions that are in your pack, and like wold said, he is going to make there be separate cartouches for the sgjourney, overworld, and generated addresses.

nope cause i found one to ad astra which isnt in my pack for glacion

**Comment by Povstalec** [comment]
> nope cause i found one to ad astra which isnt in my pack for glacion

Ah yes, the only address for which it can happen.

Not sure if I'm gonna dive into making Address Tables recognize when a dimension is or isn't present any time soon, considering it only applies to one possible address.

But in the next update it should be easier for you to find addresses, since I've got a reworked Abydos Cartouche Structure, which generates with 5 Cartouches; 1 that always has the Earth Address, 2 that always have Addresses of Dimensions added by sgjourney and 2 that always have Addresses of Nether, End or modded dimensions that aren't registered in the Stargate Network through Datapacks.

**Comment by Povstalec** [comment]
> how many gates spawn in the overworld?

2

If you want more, you can use a datapack: https://www.curseforge.com/minecraft/texture-packs/common-stargates

**Comment by Radon8472** [comment]
I am realy new with this mod, but I realy love this idea, so please excuse me when my question maybe not fits to your exiting logic..

But I would think It would be cool if there woul be a way to controll Cartuche Spawning via datapacks.
E.g. that mabe there is a default behaior that automatically adds dimensions of mods...

BUT that each modpack creator could choose e.g. custom dimension 1 should create cartuches on abydos, but dimension 2 should not.

**Comment by Povstalec** [comment]
All custom dimensions (not just modded ones) get added to the Stargate Network with a random Address and Point of Origin, if they're not added to a Solar System through a Datapack.

Okay, so when it comes to Structures, there is no custom structure for every possible combination of loot you get inside, that would be silly. There is only a LootTable that tells the game what possible Items to choose from when it's generating the loot in chests.

Cartouches work the same way, but instead of LootTables, there are AddressTables, which tell the game which Addresses (of Dimensions for now) it can choose from, and, just like LootTables, can be edited with Datapacks. So having a Dimension create new Cartouches on Abydos is entirely unnecessary, because 1) it's generated automatically and 2) if it isn't generated automatically, anyone with a basic level of Datapack knowledge will be able to generate it.

As for being able to set them to not generate, well it's a bit of a hack, but due how late Tags load in the game loading process, there isn't exactly a good way to go about doing it. Basically for Dimensions that shouldn't have Addresses that you can find on Cartouches, you just put them in custom Solar Systems, since Dimensions in registered Solar Systems don't get added to Cartouches automatically. And if you want the Dimensions to be entirely inaccessible, you can simply create a Solar System with an empty Address.
