### ISSUE TITLE
cartouches dont match up anymore

### ISSUE THREAD

**Issue by Vadewolf** [Povstalec/StargateJourney#85]
ive found new cartouches that say they go to 1 area but are for another so info needed pls also thank you so much for the change to the cartouche locations on abydos its so much more easier to atleast see them now

**Comment by Povstalec** [comment]
Can you elaborate with examples please? Because I'm not sure that "matching up anymore" is the issue.

The way Cartouches work is they store Addresses of individual Dimensions, however, multiple Dimensions can share the same Address because they are in the same Solar System, which could potentially have the effect of an Address from a Cartouche being tied to one Dimension, but Stargate Network choosing a different Dimension from the same Solar System for establishing a connection.

**Comment by Vadewolf** [comment]
basically cartouches that should have 1 adress on them have another and the coordintes dont work when dialing and i get the message "cant dial the same solar system"

**Comment by Vadewolf** [comment]
![image](https://github.com/Povstalec/StargateJourney/assets/18257282/82472f7a-673e-47f2-b3cf-5fb6a32c5924)


the 11-29 cartouche shows for overworld but is wrong its the 10-28 one thats the right one so the cartouches dont match

**Comment by Povstalec** [comment]
Ohhhhhhhhhh, right, I get it now, the two blocks are not in sync, I wonder how that happened, alright, gotta look into it

**Comment by Vadewolf** [comment]
yea also cartouches that show 1 adress in 1 location change when moved to another

**Comment by Povstalec** [comment]
Fixed it, gonna upload it in a bit

**Comment by Vadewolf** [comment]
thank you so much for the quick fix

**Comment by Povstalec** [comment]
No problem
